services:
  fdroid:
    image: austozi/fdroidserver:latest
    container_name: fdroid
    restart: unless-stopped
    user: "1000:1000"
    environment:
      TZ: Europe/London
      FDROID_REPO_ICON: fdroid.png
      FDROID_UPDATE_INTERVAL: 6h
      FDROID_REPO_URL: https://fdroid.example.com/fdroid/repo # Change me
      FDROID_REPO_NAME: F-Droid App Store
      FDROID_REPO_DESCRIPTION: An app store for Android devices.
    volumes:
      - ./fdroid:/fdroid
      - ./updates:/updates:ro
    expose:
      - 80
    networks:
      - frontend
networks:
  frontend:
