#!/usr/bin/with-contenv bash

autorefresh() {
	bash /usr/local/bin/refresh
	echo "fdroid: Last autorefresh completed `date`."
	echo "fdroid: Standing by till next autorefresh ($FDROID_UPDATE_INTERVAL)..."
	sleep $FDROID_UPDATE_INTERVAL
	autorefresh
}

autorefresh &
