#!/usr/bin/with-contenv bash

autorefresh(){
	/usr/local/bin/refresh
	echo "Last refresh completed `date`.
	Standing by till next refresh ($FDROID_UPDATE_INTERVAL)..."
	sleep $FDROID_UPDATE_INTERVAL
	autorefresh
}
autorefresh &
