#!/usr/bin/with-contenv bash

autorefresh() {
	bash /usr/local/bin/refresh
	echo "Last autorefresh completed `date`.
	Standing by till next autorefresh ($FDROID_UPDATE_INTERVAL)..."
	sleep $FDROID_UPDATE_INTERVAL
	autorefresh
}
autorefresh &
